---
name: commit

on:
  push:

jobs:
  # Inspired by https://github.com/terraform-aws-modules/terraform-aws-alb/blob/master/.github/workflows/pre-commit.yml
  get_modules:
    name: get matrix build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build matrix
        id: matrix
        run: |
          echo "::set-output name=modules::$(make glob-modules)"
    outputs:
      modules: ${{ steps.matrix.outputs.modules }}

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: terraform fmt
        uses: dflook/terraform-fmt-check@v1
        with:
          path: .

      - name: terraform validate
        uses: dflook/terraform-validate@v1
        with:
          path: .

  # Probably a better way to do this
  test-modules:
    name: test-modules
    runs-on: ubuntu-latest
    needs: get_modules
    strategy:
      fail-fast: false  # Let's see all the failing modules
      matrix:
        module: ${{ fromJSON(needs.get_modules.outputs.modules) }}
    env:
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: terraform validate
        uses: dflook/terraform-validate@v1
        with:
          path: ${{ matrix.module }}
