---
name: commit

on:
  push:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ~0.12.0
      - name: fmt
        run: terraform fmt -check -recursive
      - name: test
        run: make test
