---
name: commit

on:
  push:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Test terraform-version
        uses: dflook/terraform-version@v1

      - name: terraform fmt
        uses: dflook/terraform-fmt-check@v1
        with:
          path: .

      - name: terraform validate
        uses: dflook/terraform-validate@v1
        with:
          path: .

      # Test modules
      - name: test
        run: make test
