---
name: plan

on:
  pull_request:

env:
  AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
  AWS_DEFAULT_REGION: us-east-1
  TF_VAR_catalog_db_password: "${{ secrets.TF_VAR_catalog_db_password }}"
  TF_VAR_dashboard_db_password: "${{ secrets.TF_VAR_dashboard_db_password }}"
  TF_VAR_catalog_next_db_password: "${{ secrets.TF_VAR_catalog_next_db_password }}"
  TF_VAR_inventory_next_db_password: "${{ secrets.TF_VAR_inventory_next_db_password }}"
  TF_VAR_inventory_db_password: "${{ secrets.TF_VAR_inventory_db_password }}"
  TF_VAR_wordpress_db_password: "${{ secrets.TF_VAR_wordpress_db_password }}"
  TF_VAR_catalog_next_redis_password: "${{ secrets.TF_VAR_catalog_next_redis_password }}"
  TF_VAR_inventory_next_redis_password: "${{ secrets.TF_VAR_inventory_next_redis_password }}"


jobs:
  plan:
    name: plan
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          path: .
